// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6juHodX17S6Nb31Ih3jecInEvPxzL7SI',
    appId: '1:145233663190:web:5800e470806b371b1c6577',
    messagingSenderId: '145233663190',
    projectId: 'client1-72ef6',
    authDomain: 'client1-72ef6.firebaseapp.com',
    storageBucket: 'client1-72ef6.firebasestorage.app',
    measurementId: 'G-6KNG4TLBWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYPpMclQr8GlgKHnNNjmSIorFeeyw_B6w',
    appId: '1:145233663190:android:7178f461df367df81c6577',
    messagingSenderId: '145233663190',
    projectId: 'client1-72ef6',
    storageBucket: 'client1-72ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsOZMYuVIIB--a2WJi_5stjRpshxMbkXI',
    appId: '1:145233663190:ios:408fb90e079ebf781c6577',
    messagingSenderId: '145233663190',
    projectId: 'client1-72ef6',
    storageBucket: 'client1-72ef6.firebasestorage.app',
    iosBundleId: 'com.example.client1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsOZMYuVIIB--a2WJi_5stjRpshxMbkXI',
    appId: '1:145233663190:ios:408fb90e079ebf781c6577',
    messagingSenderId: '145233663190',
    projectId: 'client1-72ef6',
    storageBucket: 'client1-72ef6.firebasestorage.app',
    iosBundleId: 'com.example.client1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6juHodX17S6Nb31Ih3jecInEvPxzL7SI',
    appId: '1:145233663190:web:5f084922e52381c71c6577',
    messagingSenderId: '145233663190',
    projectId: 'client1-72ef6',
    authDomain: 'client1-72ef6.firebaseapp.com',
    storageBucket: 'client1-72ef6.firebasestorage.app',
    measurementId: 'G-4BYQ7QYVK2',
  );
}
